GET http://localhost:9999/clientes/1/extrato


###
GET http://localhost:9999/clientes/1/extrato


###
POST http://localhost:9999/admin/db-reset


###
POST http://localhost:9999/clientes/1/transacoes
Content-Type: application/json

{
  "valor": 1,
  "tipo": "c",
  "descricao" : "descrição"
}


###
POST http://localhost:9999/clientes/1/transacoes
Content-Type: application/json

{
  "valor": 100000,
  "tipo": "c",
  "descricao" : "descrição"
}

###

POST http://localhost:9999/clientes/1/transacoes
Content-Type: application/json

{
  "valor": 1000,
  "tipo": "c",
  "descricao" : "pix"
}


file:///home/zanfranceschi/projects/rinha-de-backend-2024-q1/load-test/user-files/results/rinhabackendcrebitossimulation-20240210024319314/index.html