###
GET http://localhost:9999/clientes/1/extrato


###

POST http://localhost:9999/clientes/1/transacoes
Content-Type: application/json

{
  "valor": 10000,
  "tipo": "d",
  "descricao" : "café"
}

###
POST http://localhost:9999/clientes/1/transacoes
Content-Type: application/json

{
  "valor": 10,
  "tipo": "c",
  "descricao" : "cre"
}

###
POST http://localhost:9999/admin/db-reset


###
GET http://localhost:9999/teste
