###
GET http://localhost:8080/clientes/9999/extrato


###

POST http://localhost:8080/clientes/1/transacoes
Content-Type: application/json

{
  "valor": 10,
  "tipo": "d",
  "descricao" : "01234567890123456789012345678901234567890123456789"
}

###
POST http://localhost:8080/clientes/1/transacoes
Content-Type: application/json

{
  "valor": 10,
  "tipo": "c",
  "descricao" : "[1, 2]"
}

###
POST http://localhost:8080/admin/db-reset


###
GET http://localhost:8080/teste
