version: "3.5"

services:
  api01: &api
    image: zanfranceschi/rinha-2024q1-crebito
    hostname: api01
    environment:
      - DB_HOSTNAME=localhost
      - PORT=3001
    network_mode: "host"
    expose:
      - "3001"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "200MB"

  api02:
    <<: *api
    hostname: api02
    environment:
      - DB_HOSTNAME=localhost
      - PORT=3002
    network_mode: "host"
    expose:
      - "3002"
 
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    network_mode: "host"
    expose:
      - "9999"
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "10MB"

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    network_mode: "host"
    expose:
      - "5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "140MB"
