version: "3.5"
services:
  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    expose:
      - "5432"
    volumes:
      - ../ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "200MB"
