version: "3.5"

services:
  api01: &api
    image: rinha-concurrency-control
    hostname: api01
    environment:
      - DB_HOSTNAME=localhost
      - HTTP_PORT=8081
    expose:
      - 8081
    #ports:
    #  - "8081:8080"
    depends_on:
      - db
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "150MB"

  api02:
    <<: *api
    hostname: api02
    environment:
      - DB_HOSTNAME=localhost
      - HTTP_PORT=8082
    expose:
      - 8082
    #ports:
    #  - "8082:8080"
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    #ports:
    #  - "9999:9999"
    expose:
      - 9999
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "100MB"

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    #ports:
    #  - "5432:5432"
    expose:
      - 5432
    volumes:
      - ./ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "200MB"

#networks:
#  default:
#    driver: bridge
#    name: cc
