version: "3.5"

services:
  api01: &api
    image: zanfranceschi/rinha-2024q1-crebito
    hostname: api01
    environment:
      - DB_HOSTNAME=db
      - PORT=3000
    ports:
      - "3001:3000"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "200MB"

  api02:
    <<: *api
    hostname: api02
    environment:
      - DB_HOSTNAME=db
      - PORT=3000
    ports:
      - "3002:3000"
  
  haproxy:
    image: haproxy:2.9-alpine
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.17"
          memory: "10MB"

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ../db/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "140MB"

networks:
  default:
    driver: bridge
    name: rinha-haproxy-2024q1
